# Generated by Django 2.2.16 on 2020-10-20 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('cod', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=30)),
                ('imagen', models.ImageField(null=True, upload_to='empleados')),
            ],
        ),
        migrations.CreateModel(
            name='Instalacion',
            fields=[
                ('cod', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('direccion', models.TextField()),
                ('imagen', models.ImageField(null=True, upload_to='instalaciones')),
            ],
        ),
    ]
